### ISSUE TITLE
一些个人认为还不够完美的地方

### ISSUE THREAD

**Issue by kooguma** [Bigmercu/PerfectModel#2]
1.onCancel() 方法一直没有去调用，Subscription 没有 unsubscribe 。考虑所有的ModelImpl都要去做这个操作，是否显得太麻烦？感觉MVP模式搭上RxLifeCycle是个不错的选择。
2.个人认为，可以配置下Retrofit，添加GsonConverterFactory，并使用注解@JsonAdapter。以免去所有的ModelImpl中，用来注册TypeAdapterFactory和map的操作。
说的不正确的地方欢迎指出哈～

**Comment by Lswks** [comment]
感谢你提出的建议：
已经优化了第二点，之前没了解过RxLifeCycle，今天做了一些了解，发现它对MVP不是特别友好（在MVP里不易用），我明天会继续看看这方面，希望能找出一个好的解决办法。

**Comment by Lswks** [comment]
再次感谢你提出建议，所有建议的地方均已优化。
