### ISSUE TITLE
求分享一下您的retrofit上传下载带进度的封装方法

### ISSUE THREAD

**Issue by ynheng** [Bigmercu/PerfectModel#3]
dear：
在简书留言板中看到您在别人帖子上的留言（不错哦，我还有另外一种封装的更好的，明天发一篇文章分享。）
正巧我也在寻求一种好的方法，所以请您不吝分享一下，以供学。
各个地方也找不到您的联系方式，只好在此开个issues，希望联系到您，非常感谢！！

**Comment by Lswks** [comment]
我邮箱是 bigmercu@gmail.com ^_^
